unchained-capital/caravan

- src/components/Spend/styles.module.scss
`height` was not allowing to expand and show the errors, changed to `min-height`.
> Fix output errors being covered up

- src/components/ClientPicker.jsx
Makes a simple call ignoring the result, display error message or success.
> Add button to test private node connection to client picker

- src/components/ScriptExplorer/ConfirmOwnership.jsx
Fix this when confirming ownership:
```
Warning: Failed prop type: Invalid prop `labelId` of type `boolean` supplied to `ForwardRef(Select)`, expected `string`.
in ForwardRef(Select) (created by WithStyles(ForwardRef(Select)))
in WithStyles(ForwardRef(Select)) (at ConfirmOwnership.jsx:229)
in div (created by ForwardRef(FormControl))
in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
in WithStyles(ForwardRef(FormControl)) (at ConfirmOwnership.jsx:226)
in form (at ConfirmOwnership.jsx:223)
in div (created by ForwardRef(CardContent))
in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
in WithStyles(ForwardRef(CardContent)) (at ConfirmOwnership.jsx:222)
in div (created by ForwardRef(Paper))
in ForwardRef(Paper) (created by …
```
> Fix proptypes error on confirming ownership select.

- .travis.yml
- package.json
The travis build was building caravan but wasn't linting and running
tests.  This commit fixes the jobs.
> Fix travis build to lint and run tests (again).

- src/components/ImportAddressesButton.jsx
- src/components/Slices/SliceDetails.jsx
- src/components/Wallet/ExtendedPublicKeyImporter.jsx
- src/components/Wallet/WalletActionsPanel.jsx
- src/components/Wallet/WalletGenerator.jsx
- src/components/Wallet/WalletInfoCard.jsx
- src/components/Wallet/index.jsx
- src/proptypes/slice.js
Move wallet actions to their own panel at top of wallet view. Required some refactoring of code where some actions and state were being handled in child components. Moved these up into the main wallet container so this state could be shared. 
Added a tooltip for the clear wallet button to make clear that this doesn't clear any funds from the wallet but only clears state from the browser session.
this is what it looks like for private clients (includes the import button)
And this is what it is for public clients (without important button)
> Move wallet actions into panel at the top of wallet view

- src/components/ScriptExplorer/ScriptEntry.jsx
- src/reducers/transactionReducer.js
- src/utils/constants.js
Catches a bug where the `handleChangeAddressAndDust` function was returning updated state differently under certain code paths. This was causing an error to be thrown in cases where change was less than dust OR if the change output index was 0.
> make function return objects consistent in transaction reducer

- src/components/CreateAddress/ExtendedPublicKeyPublicKeyImporter.jsx
Remove extraneous '(' from the form to derive a pub key from an xpub
when creating an address.
> Fix typo when deriving a public key from an xpub.

- src/components/ScriptExplorer/OutputsForm.jsx
- src/reducers/transactionReducer.js
There were certain edge cases where the estimated fee display would show in scientific notation. While I couldn't find a way to replicate the circumstances where I first saw this, and therefore don't know for sure if this solves the original issue, I could get the same result by having a fee rate at a fraction of a satoshi (i.e. 0 < n < 1). The function that needed to be fixed was used in several places and so I believe this should catch the underlying issue (which seemed to need a BigNumber that was then converted to a fixed float string). 
In addition, I made the fee rate explicitly a number type html input to avoid the situations where we would get NaN and set a step value as an integer to make it easier to avoid decimal points. There is also a validation check now in the …
> Fix fee calculation display with scientific notation

- src/components/ClientPicker/index.jsx
- src/components/CreateAddress/index.jsx
- src/components/ImportAddressesButton.jsx
* Selecting private node on script explorer page hits your node with many requests per second 
* Switching client from public to private causes TypeError after importing public keys
The first was fixed by not running the check whenever the `enableImport` state was changed this his happened in the effect too and so created an infinite loop until a connection succeeded. 
The second was fixed by always showing the client selector and making sure it is passed the correct props.
> Fix private client connection bugs

- src/components/Wallet/WalletSign.jsx
- src/components/Wallet/WalletSpend.jsx
This change fixes some weird/unexpected behavior in the wallet view when switching between tabs at different stages of a wallet spend.
The issue seemed to come from how the react component lifecycle methods were being used to call the `selectCoins` method causing some asynchronous calls to the redux dispatcher. This ended up clearing some parts of the store, causing some re-renders in components before the state was properly updated. 
This change is more selective about when to reset the state, in particular making sure that coin selection happens only if the props change, the view in autoSpend mode, AND the outputs are not finalized. 
Also if the wallet spend view is unmounted (i.e. when the tab changes) and the tx has been spent, then the `spend.transaction` part of the state is reset. …
> better state management in WalletSpend components

- .github/pull_request_template.md
Now that we're using commitizen we don't need the first part of
the PR template.  Removing to make it shorter.
> docs(other): remove PR type from PR template

- package-lock.json
- src/actions/transactionActions.jsx
- src/actions/walletActions.jsx
- src/components/AppContainer.jsx
- src/components/Copyable.jsx
- src/components/ScriptExplorer/OutputEntry.jsx
- src/components/ScriptExplorer/OutputsForm.jsx
- src/components/ScriptExplorer/styles.module.scss
- src/components/Wallet/TransactionPreview.jsx
- src/components/Wallet/WalletControl.jsx
- src/components/Wallet/WalletGenerator.jsx
- src/components/Wallet/WalletSpend.jsx
- src/proptypes/index.js
- src/proptypes/slice.js
- src/proptypes/utils.js
- src/reducers/transactionReducer.js
- src/reducers/transactionReducer.test.js
- src/selectors/wallet.js
- src/selectors/wallet.test.js
- src/utils/constants.js
- src/utils/fixtures.js
- src/utils/index.jsx
- src/utils/utils.test.js
This is a rewrite of the spend UX and includes a re-factor of the coin selection functionality. With this new update, coin selection (and fee calculation) happens after outputs have been selected and the user clicks to preview the transaction. This should fix several bugs that seem related to some race conditions if the view was changed while a tx was being composed in auto spend mode. 
This should not introduce a breaking change, but the whole spend flow will need to be tested thoroughly, including manual mode and from the script explorer.
> feat (wallet): synchronous auto spend and coin selection + max spend

- src/actions/walletActions.jsx
- src/components/Wallet/WalletSign.jsx
Only update the spend transaction slices after the transaction confirmation/preview component has unmounted. This gives querying node enough time to update its mempool state and return accurate information about the queried slices. 
This also adds a small upgrade to include the next deposit slice in this update step. This means that self-spends to your own wallet (as long as it's the latest address from the receive tab) will be reflected in the UI without a refresh.
>  fix(wallet): update spending slices when WalletSign component unmounts

- src/components/Wallet/WalletSpend.jsx
clears inputs and change when switching between spend modes as these don't translate between the two states and can distort calculations for tx values.
> fix(wallet): fixes display error in totals when switching b/w spend modes

- src/actions/walletActions.js
- src/components/Wallet/TransactionPreview.jsx
- src/components/Wallet/WalletSign.jsx
- src/reducers/braidReducer.js
This PR fixes a bug where slice updates for inputs and outputs (most importantly the change) weren't being queried or updated properly after a spend resulting in incorrect wallet balances requiring a refresh to show properly. 
The issue was the state was being updated during other action calls that didn't need to be made anymore. Specifically a change output was assumed and updated manually without waiting for a response which bumped the "nextNode" for change, confusing the state for when they were being checked against a bitcoin client. The code causing this was cleaned up as well as using some recursion in the event that the call didn't return any updates to check again (checking a total of 5 times). 
Fixes: #104
> fix(wallet): fixes inconsistencies in wallet balance update after spend

- README.md
- src/components/ClientPicker/index.jsx
- src/components/ScriptExplorer/SignatureImporter.jsx
- src/components/Wallet/WalletGenerator.jsx
- src/components/Wallet/index.jsx
Client and signing method may not be known by an external coordinator that can produce Caravan configs, these fields should be optional in the config, and gathering that information from the user should happen cleanly.
This PR adds that functionality.
During wallet config import, if client information is not included, the ClientPicker is displayed with no selection and the wallet cannot be initialized until a selection is made. This is to stop a user from accidentally using a public node if they would have preferred to use a private node.
If a signing method isn't included in the config, the method selector dialog is shown during signing (very similar to the 'enter as text' option), but the BIP32 path that was included in the config is used, unlike the 'enter as text' option.
Also, if a …
> Make client and method optional in wallet config file

- package-lock.json
- package.json
- src/actions/settingsActions.js
- src/components/StartingAddressIndexPicker.jsx
- src/components/Wallet/ConfirmWallet.jsx
- src/components/Wallet/WalletGenerator.jsx
- src/components/Wallet/index.jsx
- src/reducers/settingsReducer.js
Caravan is now aware of the starting address index. 
When loading a wallet config caravan will jump ahead to the starting address index.
When creating a new wallet, a new Starting Address Index Picker is available.
#149
> feat(wallet): starting Address Index loading, picking, exporting

- CHANGELOG.md
The changelog was generated incorrectly in 3.0 because of rebasing
to include the summary.  In order to fix I had to allow the
standard-version tool to add the changelog from 3.0 again.  This
commit removes the duplicate 3.0 changes and adds a note about
updating unchained-wallets.
> chore(other): fix incorrectly generated changelog

- package-lock.json
- package.json
5000 low severity vulnerabilities were found while installing node modules. Such a message might intimidate uninformed users, so I bumped the dependencies to fix all but one vulnerability without breaking the code.
I simply ran `npm audit fix` to bump the versions of dependencies with vulnerabilities, and committed the package*.json 
Similar to #134
> fix(other): fix npm packages with low severity vulnerabilities

- package.json
Instead of using commitlint -e which checks the last commit from
.git/COMMIT_EDITMSG use --from which checks actual changelog
history.
> build(other): make commitlint check latest commit

- src/selectors/wallet.js
- src/utils/slices.js
- src/utils/slices.test.js
Before this change, sorting adresses by Last used date didn't work correctly in countries where default date format is e.g. DD.MM.YYYY (1.3.2020 was displayed before 7.11.2019 and that was shown before 9.3.2020). This pull request fixes this problem by comparing last used dates as unixtimes and not as localized strings (returned by toLocaleDateString() method).
Furthermore, previously when lastUsed property wasn't initialized for individual addresses, corresponding value (that was later used for comparison) was calculated as minimum of times of individual utxos - which would be the time when the adress was used for the first time and not for the last time.
> fix(slices): use unixtime to compare lastUsed dates

- .github/workflows/main.yml
- CONTRIBUTING.md
Use a github action to deploy the build to github pages after a
release is created.
> build(other): add gh action for deploying release

- src/components/Wallet/WalletGenerator.jsx
ISSUES: #109
Bug fix for an open issue (#109) where the Edit Details button would clear the wallet when clicked. It now directs back to the editable xpubs page.
#109
> fix(wallet): direct Edit Details btn to editable pubkey page

- README.md
- bitcoind.proxy
[`corsproxy`](https://www.npmjs.com/package/corsproxy) is no longer maintained and is failing build. CORS headers are not provided from [bitcoin-core](https://github.com/bitcoin/bitcoin/pull/12040) and so a supported alternative is needed. A reference configuration for the `nginx` reverse proxy is provided that adds the needed CORS header. CORS implementation instructions were revised to be consistent with the new method. 
ISSUES: 209
1. In the root `README.md`, `corsproxy` is no longer maintained on the npm website https://www.npmjs.com/package/corsproxy is listed as build failing, having been last updated 4-years ago.
2. All references for ` corsproxy` were removed from `README.md`
3. `README.md` was updated with implementation instructions for Debian and MacOS.
4. An `nginx` …
> fix(other): replace corsproxy with nginx reverse proxy

- package-lock.json
- package.json
- src/components/CreateAddress/AddressGenerator.jsx
- src/components/CreateAddress/PublicKeyImporter.jsx
- src/components/CreateAddress/TextPublicKeyImporter.jsx
- src/utils/index.js
- src/utils/utils.test.js
Handling the error when an uncompressed public key is given to address types P2WSH or P2SH-P2WSH
ISSUES: https://github.com/unchained-capital/caravan/issues/164
Demo video:
https://user-images.githubusercontent.com/76526363/103631741-a97ee180-4f43-11eb-93dd-10a23ecdcb52.mp4
Thank for taking a look & sending feedbacks my way :)
> fix(pubkeyimporter): jS error when using Enter as text with incorrect access type

- src/components/Coldcard/ColdcardFileReader.jsx
Per spec `psbt` file is actually in binary. Support this while continuing to support base64/hex as well.
> fix(wallet): handle binary psbt properly

- src/components/ScriptExplorer/OutputsForm.jsx
- src/components/ScriptExplorer/UTXOSet.jsx
- src/components/Slices/SliceDetails.jsx
- src/components/Wallet/AddressExpander.jsx
Allow UTXO selection on spend. Works in both Redeem Script and Wallet interfaces but the Wallet interface is not 100% feature complete. E.g. if you try to spend a single utxo from multiple addresses that will not work properly right now. However, within a multi-address setup, you should be able to do coin selection.
Partially addresses https://github.com/unchained-capital/caravan/issues/54
> fix(wallet): basic coin selection on spend

- src/components/CreateAddress/ExtendedPublicKeyPublicKeyImporter.jsx
- src/components/CreateAddress/HardwareWalletPublicKeyImporter.jsx
- src/components/CreateAddress/HermitPublicKeyImporter.jsx
- src/components/CreateAddress/PublicKeyImporter.jsx
- src/components/CreateAddress/TextPublicKeyImporter.jsx
This is a partial fix to https://github.com/unchained-capital/caravan/issues/126 (partial because it doesn't address the scripts explorer page but only the addresses generator). 
The problem stated in the issue stems from the fact that the BIP 32 path and error are stored on different states (the path in redux, the error as part of the local state). My approach to fixing the issue involves moving the BIP 32 path to the local state so that it always changes at the same time as the error message. This has a couple of advantages:
* state and validation lives in a single place
* we hit the redux state only when the public key is valid (= better performance while editing in a single importer)
If you like the approach I'd be happy to open a similar PR for the scripts explorer page. …
> Fix BIP 32 input in address generator 

- package-lock.json
- package.json
- src/components/ScriptExplorer/UTXOSet.jsx
- src/components/Wallet/AddressExpander.jsx
- src/components/Wallet/Node.jsx
- src/components/Wallet/NodeSet.jsx
- src/components/Wallet/WalletSpend.jsx
Allow UTXO selection on manual spend in Wallet interface.
Fixes #54 
Follow-up to https://github.com/unchained-capital/caravan/pull/221 - adds in the necessary logic to handle utxo selection across multiple addresses
> fix(wallet): adds utxo selection to manual spend on wallet interface

- .github/workflows/main.yml
Fix the release gh action by running apt update before install.
Fixes [this](https://github.com/unchained-capital/caravan/runs/3187209224?check_suite_focus=true):
```
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libudev-dev amd64 245.4-4ubuntu3.7
404  Not Found [IP: 52.154.174.208 80]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libusb-1.0-0-dev amd64 2:1.0.23-2build1 [64.4 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libusb-1.0-doc all 2:1.0.23-2build1 [172 kB]
Fetched 237 kB in 0s (2919 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_245.4-4ubuntu3.7_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Unable to fetch some archives, maybe run apt-get update or try with …
```
> build(other): fix release build gh action

- package.json
Node 15+ are not supported by our current version of node-sass, 4 - the build fails when the two are
combined. By explicitly declaring that version as unsupported, we better communicate the issue.
https://www.npmjs.com/package/node-sass
Note 16 is the current "latest" release, 14 is the current "lts" release.
https://nodejs.org/en/
> build(deps): disallow node 15 and above via engines and enginesStrict

- package-lock.json
- package.json
- src/tests/signing.jsx
New Coldcard firmware grinds signature nonces to output smaller signatures. Fixtures updated in `unchained-bitcoin` and branch on `keystore === COLDCARD` ... means old firmware wont work now, but way code is structured means it's either or.
Old firmware signatures from Coldcard won't pass the test suite anymore.
> fix(testrunner): handle coldcard now emitting low-s signatures

- README.md
The issues link in the README.md for Caravan does not go to the issues page.  This update implements the correct URL.
* [ X ] No
* [X ] No
> docs(other): Fix broken link to Caravan GitHub Issues in README.md

- Dockerfile
- README.md
Adds a basic dockerfile which builds the app and serves it via nginx.
Future work could include automating the build and publish of this image to dockerhub.
Even further future work could include making caravan available as an umbrel app.
> Add basic Dockerfile to build and serve the app

- package-lock.json
- package.json
- src/actions/walletActions.js
- src/components/RegisterWallet/DownloadColdcardConfig.jsx
- src/components/RegisterWallet/PolicyRegistrationsTable.jsx
- src/components/RegisterWallet/RegisterLedgerButton.jsx
- src/components/RegisterWallet/index.jsx
- src/components/ScriptExplorer/DirectSignatureImporter.jsx
- src/components/ScriptExplorer/SignatureImporter.jsx
- src/components/Slices/ConfirmAddress.jsx
- src/components/Slices/SliceDetails.jsx
- src/components/Wallet/ConfirmWallet.jsx
- src/components/Wallet/RegisterWallet.jsx
- src/components/Wallet/WalletGenerator.jsx
- src/components/Wallet/index.jsx
- src/proptypes/wallet.js
- src/reducers/walletReducer.js
- src/selectors/wallet.js
- src/tests/addresses.jsx
- src/tests/registration.jsx
This starts to leverage new features introduced with Ledger's new bitcoin app that supports multisig wallet policy registration. Major features being introduced are explicit wallet registration, using a new serialization of ledger policy hmacs in the wallet config, and address verification. 
Requires an update to [unchained-wallets](https://github.com/unchained-capital/unchained-wallets/pull/99). This branch pinned to the working branch of uc-wallets and should be updated when that is published. 
New features:
- Main wallet entry page (where you confirm wallet details before viewing the wallet itself) has policy information and ability to register the wallet with device (coldcard and ledger supported)
- Can persist registration in local state to be downloaded via wallet config file
- …
> Wallet registrations and address verification

- .gitignore
- package-lock.json
- package.json
- src/actions/walletActions.js
- src/components/Wallet/RegisterWallet.jsx
- src/components/Wallet/index.jsx
- src/reducers/walletReducer.js
- src/selectors/wallet.js
Wallet configs needed explicit support for uuids now that there are wallet registrations. Names can be edited so there needs to be an identifier that can be assumed to not be editable. The config type does support an optional uuid. This makes sure to save this value in state and use it in the registration if possible. This will also need some dependency bumps to uc-bitcoin and uc-wallets that are forthcoming. The uc-wallets update will also make it so that the registration isn't malleable in another way- changing key order. 
deploying this to a test environment to try it. https://bucko13.github.io/caravan/#/help 
If you don't see the commit hash [2e7024b](https://github.com/unchained-capital/caravan/pull/297/commits/2e7024b241950a7ce2e9626712130d0f0f2ac8c5) in the bottom right, make sure …
> feat: add support for wallet uuid in configs

- src/components/Wallet/RegisterWallet.jsx
This got caught in some testing I was doing to figure out local npm link issues with vite. h/t @dylanbathurst who caught this.
> fix: bad import

- src/components/ScriptExplorer/ScriptEntry.jsx
For a new wallet no UTXO's can be found. This results in an uninformative error message. The message is now changed to having 0 balance.
ISSUES: #172
> fix(scriptexplorer): Change the error message for spending from new wallet

- src/block_explorer.js
Add delay to calls to block explorer to prevent blockstream throttling.
TODO FIXME HACK
ISSUES: #317
> fix(wallet): add delay to address and utxo calls

- src/components/ScriptExplorer/SignatureImporter.jsx
Turns out that the wallet uuid which is used now for ledger wallet registrations wasn't getting passed for signing and so the registration was failing validation.
I think this still needs to be fixed in the test suite though unfortunately and possibly at the fixture level (from unchained-bitcoin). But this gets signing working at least.
> fix(sign): pass wallet uuid for signing

- README.md
- src/components/ClientPicker/index.jsx
- src/components/Help.tsx
Replace a couple of usages of blockstream.info with mempool.space.  Should be merged after https://github.com/unchained-capital/unchained-bitcoin/pull/99.
Also remove delay hack added in d9774c1c7e28021a48efa30666c6ceb9e75cd1da as it's not needed now that we're using mempool.space.
> chore: s/blockstream.info/mempool.space/g

- package-lock.json
- package.json
- src/components/ScriptExplorer/OutputsForm.jsx
- src/reducers/transactionReducer.js
This updates unchained-bitcoin to v1.2.0
This change uses the new fee error types provided by unchained-bitcoin v1.2.0 to conditionally display fee error feedback. The conditional in this case is that `FeeValidationError.FEE_RATE_TOO_HIGH` is going to be ignored to allow for CPFP transactions to be authored in a high fee environment. A caption has been added to the fee rate input instructing the user to be responsible in researching fee rate acceptance on their own.
Perhaps partially: https://github.com/unchained-capital/caravan/issues/169
> Unblock fee rate limit, add caption warning about mempool monitors

- package.json
The commit hash wasn't getting built properly for prod builds. This updates the npm script to work the same as dev builds by making sure the string is in the right session. 
Before ([current deployment](https://unchained-capital.github.io/caravan/#/help)):
Tested with a build [here](https://bucko13.github.io/caravan/#/help)
> fix(build): pass git sha to build properly

- package-lock.json
- package.json
Fixes a bug with trezor address verification. A change to trezor connect broke the api. the fix in uc-wallets was to pin the connect iframe app it uses to interact with the device. 
Here's a successful address verification
> fix(dependencies): bump uc-wallets for trezor fix
