unchained-capital/caravan

README.md
src/components/ClientPicker.jsx

Fixed broken CORS doc link

---

src/components/Spend/OutputsForm.jsx
src/components/Spend/SignatureImporter.jsx
src/components/Spend/Transaction.jsx

This disables the button.  Disabling triggered a `componentDidUpdate` which caused undesirable scrolling so that was fixed too.

Disable remove signature on broadcast

---

src/components/Spend/OutputsForm.jsx

Icon disabled just like the rest of the output items

No estimate rate gathering signatures

---

src/components/CreateAddress/index.jsx
src/components/MultisigDetails.jsx
src/components/Spend/SignatureImporter.jsx
src/components/Spend/Transaction.jsx
src/components/Spend/index.jsx
src/components/styles.css

There was overlap in Firefox and signatures extending beyond container, this fixes both

Fix wrapping issues

---

src/components/ScriptExplorer/OutputsForm.jsx
src/reducers/transactionReducer.js
src/reducers/transactionReducer.test.js

this PR fixes a bug where input and output address for a spend could be the same. It also fixes tests that had broken in the course of dev of wallet.

Input address bug

---

src/components/Help.jsx

Fix this error on the index page:
```
Warning: Failed prop type: Invalid prop `type` of value `secondary` supplied to `ForwardRef(ButtonBase)`, expected one of ["submit","reset","button"].
in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(Button))
in ForwardRef(Button) (created by WithStyles(ForwardRef(Button)))
in WithStyles(ForwardRef(Button)) (at Help.jsx:195)
in div (created by ForwardRef(CardActions))
in ForwardRef(CardActions) (created by WithStyles(ForwardRef(CardActions)))
in WithStyles(ForwardRef(CardActions)) (at Help.jsx:191)
in div (created by ForwardRef(Paper))
in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
in …
```

Fixes JS error on the help card.

---

src/components/ScriptExplorer/OutputEntry.jsx

Fixes JS error on the output entry form when constructing a transaction.

Fix proptype error on the script explorer.

---

src/components/Help.jsx

Fix this typo `Caravan is alsostateless`.

Fix typo on help page

---

package-lock.json
package.json
src/components/App.jsx
src/components/Copyable.jsx
src/components/Wallet/WalletDeposit.jsx

Use notistack for notifications and add a notification when copying a `<Copyable>`.  Also remove unused `<ErrorNotification>` component.

Add notistack for notification handling.

---

.gitignore
src/components/Help.jsx
src/components/Navbar.jsx

Based on feedback, adding some UI pieces to improve initial navigation flow.

add title to navbar icon and start panel on homepage

---

.gitignore
package-lock.json
package.json
src/actions/walletActions.jsx
src/components/Copyable.jsx
src/components/Slices/SliceDetails.jsx
src/components/Slices/SlicesTable.jsx
src/components/Slices/SlicesTableContainer.jsx
src/components/Slices/index.js
src/components/Wallet/WalletControl.jsx
src/components/Wallet/WalletDeposit.jsx
src/proptypes/index.js
src/proptypes/settings.js
src/proptypes/slice.js
src/reducers/braidReducer.jsx
src/reducers/index.js
src/selectors/wallet.js
src/utils/slices.js

Several updates and fixes included in this PR:
* Uses new SlicesTable for displaying Addresses List
* Fixes bug in Receive view where the address wouldn't update after deposit was received
* Refactor WalletDeposit to use selectors for keeping track of "depositable" addresses and updating when deposit is received
* Updates to the Slices Table to support additional functionality in the address list view, namely: sorting, filtering, different display of spent addresses, and a container that connects the table to the redux store.
* Code update for using "slice" in favor of "node" in more places.

Address list

---

src/components/App.jsx
src/components/CreateAddress/PublicKeyImporter.jsx
src/components/Help.jsx
src/components/Hermit/HermitDisplayer.jsx
src/components/Hermit/HermitReader.jsx
src/components/InteractionMessages.jsx
src/components/Navbar.jsx
src/components/ScriptExplorer/SignatureImporter.jsx
src/components/ScriptExplorer/Transaction.jsx
src/components/Slices/SlicesTableContainer.jsx
src/components/UnsignedTransaction.jsx
src/components/Wallet/ExtendedPublicKeyImporter.jsx

Mostly cosmetic changes based on feedback:
- fixed doubled text on copyable elements and add icon where relevant
- update text on landing page buttons
- fix landing page button links
- change /create -> /address for consistency
- change Version -> Model on import views

cosmetic changes:

---

src/components/Help.jsx

Put the icons at the start of the button like elsewhere in the
application.

Fix button icons on the help page.

---

src/components/Wallet/WalletDeposit.jsx

Instead of copying bitcoin:<addr> copy just the <addr> when clicking on
the wallet receive QR code.

Copy address when clicking on QR code.

---

src/components/Wallet/TransactionPreview.jsx
src/components/Wallet/WalletSpend.jsx

* [] Bug fix
Signify which output is the change on the transaction preview page:

Denote change output on transaction preview page.

---

src/components/Footer.jsx
src/components/Slices/SlicesTableContainer.jsx
src/components/Wallet/TransactionPreview.jsx
src/components/Wallet/WalletDeposit.jsx
src/components/Wallet/WalletSpend.jsx
src/reducers/transactionReducer.js

- Remove the return button on the receive page
- Left justify send/preview transaction buttons to match elsewhere
- Move edit transaction button to bottom
- Fix error message when output is greater than balance
- Move wallet tabs into cards to make them consistent
- Fix alignment of footer

Fix some styling issues

---

src/utils/slices.js
src/utils/slices.test.js

There was a bug in sorting slices by time when zero balance and spent were included in the table. 
Also added tests for that particular sort function to clarify what the expectations are (and hopefully catch bugs earlier in the future).

fix sort by time bug and add tests

---

src/components/ScriptExplorer/OutputsForm.jsx

Show short message about change in order to make it clear that the
output includes change.
Change highlighted in the following screenshot:

Add message about change to simple wallet page

---

src/components/CreateAddress/AddressGenerator.jsx

`2-of-3 MultisigP2SH` vs `2-of-3 Multisig P2SH`

Fix minor spacing issue on create address page.

---

src/components/Slices/SlicesTable.jsx
src/components/Wallet/Node.jsx
src/components/Wallet/WalletGenerator.jsx

UI update changing the prefix for the BIP32 Paths displayed in the slice table.

update path notation

---

src/actions/walletActions.jsx
src/components/Slices/SlicesTableContainer.jsx
src/components/Wallet/WalletInfoCard.jsx
src/components/Wallet/WalletSign.jsx
src/components/Wallet/index.jsx
src/reducers/braidReducer.jsx
src/selectors/wallet.js
src/selectors/wallet.test.js
src/utils/constants.js
src/utils/slices.js
src/utils/slices.test.js

Fixes bug where incoming transaction is being shown both in confirmed balance total as well as in the +<amount> green text

Pending balance fix

---

package.json
src/components/Help.jsx

Update the help page with new copy and devices links and updates the
version to 0.2.0.

Update help page and package.json for v0.2.0.

---

package.json
src/components/AppContainer.jsx
src/index.jsx
src/reducers/addressReducer.jsx
src/reducers/index.js
src/reducers/quorumReducer.jsx

Clears the state between route changes. This helps fix some bugs where different routes were sharing state that wasn't being properly updated or cleared.

clear app state when switching routes

---

src/reducers/quorumReducer.jsx

This fixes a bug where the app was not properly updating the views if the quorum was changed part way through importing keys.
To reproduce: 
1. Go to the setup wallet page
2. Import 2 keys
3. Reduce the total in the quorum to 2
4. Attempt to clear the wallet
5. Note you are shown the confirm page

update quorum state if total signers count changes

---

src/components/ClientPicker/index.jsx
src/components/ScriptExplorer/TextSignatureImporter.jsx

Catch JSON.parse errors to fix FF crash

catch JSON.parse error

---

.commitlintrc.json
.cz-config.js
package-lock.json
package.json

Add commitlint and commitzen to the project in preparation for semantic releases.

chore(other): adds commitlint and commitzen

---

CHANGELOG.md

Adds a manually generated changelog.md to caravan for prior releases.

chore(other): add changelog.md to the project

---

CONTRIBUTING.md
README.md
package.json

Adds CONTRIBUTING.md to the project and links it from README.md.
Also fixes small typo in package.json
Requires https://github.com/unchained-capital/caravan/pull/52.

docs(other): add contribution steps and guidelines to the project

---

package-lock.json
package.json
src/components/Wallet/WalletGenerator.jsx
src/reducers/transactionReducer.test.js

Bump up unchained-bitcoin for the more exact fee estimation functionality.

upgrade unchained-bitcoin

---

package-lock.json
package.json

Updating unchained-wallets version.

chore(other): update unchained-wallets to 0.0.12

---

.github/issue_template.md
.github/pull_request_template.md
CHANGELOG.md

Need to merge master into wallet dev so I can update `.pull_request_template.md` in the wallet dev branch.

Merging changes from master into wallet dev.

---

package.json

Fix the test coverage reporting in the CI.

chore(other): fix test coverage for ci runs

---

.eslintrc
package-lock.json
src/components/EditableName.jsx
src/components/Wallet/WalletInfoCard.jsx
src/components/Wallet/__tests__/WalletInfoCard.text.jsx
src/components/__tests__/EditableName.test.jsx

Add tests for WalletInfoCard and EditableName.
Also fix a couple of minor bugs found by tests:
- Autofocus editable name text field
- Remove unused children prop from WalletInfoCard
Depends on https://github.com/unchained-capital/caravan/pull/80

test(wallet): WalletInfoCard and EditableName

---

src/components/App.jsx

Redirects old path /spend to the new script page

fix(other): redirect requests to /spend path

---

public/index.html

fix(other): update page title to "Caravan"

---

src/bitcoind.js
src/reducers/addressReducer.jsx
src/tests/index.js

Addresses some comments in the wallet-dev PR #27 
(in the pr comments)

fix(other): Cleanups from pr comments

---

cypress/integration/HelpPage.spec.js
src/components/Help.jsx

docs(other): updates the caravan blog post link on the help page

---

public/index.html

fix(other): update html meta description text

---

.cz-config.js

Update the available components in commitizen.

docs(other): update the list of components when running commitizen

---

package-lock.json
package.json

Bump unchained wallets to the latest version.

Bumps unchained-wallets to v0.1.1

---

src/components/Slices/ConfirmAddress.jsx

Wallet configs omitting method from xpubs can now use Confirm on Device
A device-picking dialog is shown if method == 'unknown' with all but Trezor disabled

fix(slices): confirmAddress can handle unknown method

---

package-lock.json
package.json

Update unchained-wallets to 0.1.2

chore(other): update unchained-wallets to 0.1.2

---

package-lock.json
package.json

Update some dev dependencies to the latest versions that were
missed as part of the last udpate.

chore(other): update additional dev-dependencies

---

CONTRIBUTING.md
package-lock.json
package.json

Use standard-version to update CHANGELOG.md with changes from the
release and version everything accordingly.
Adds an npm run release command to combine standard-version with
GitHub pages deployment.

chore(other): adds standard-version release script

---

package-lock.json
package.json

Update unchained-wallets to 0.1.3.

chore(other): update unchained-wallets to 0.1.3

---

package-lock.json
package.json

bumping unchained-wallets dependency
no

chore(other): bump unchained-wallets to 0.1.6

---

.cz-config.js
.github/pull_request_template.md

Make commit catagories clearer and fix a typo in the pull request
template.

docs(other): fix typo and update commit catagories

---

CHANGELOG.md

Update the changelog to show the updates to unchained-wallets.  This
shouldn't be necessary in the future because of the recent changes to
the commitizen configuration.

docs(other): fix changelog to show dependencies

---

package-lock.json
package.json

Update unchained-bitcoin to 0.0.15 and unchained-wallets to 0.1.7.

fix(dependencies): update unchained libraries

---

package-lock.json
package.json

Update out of date dependencies using npm audit fix.  This fixes
all but two vulnerabilities.  I will fix the other two in a
separate change.

fix(dependencies): update deps with npm audit fix

---

package-lock.json
package.json

Fix two vulnerabilities in dependencies with breaking changes using
npm audit --force.
Requires https://github.com/unchained-capital/caravan/pull/179

fix(dependencies): two deps with breaking changes 

---

src/components/TestSuiteRun/Seed.jsx

Fix a couple of typos on the cold card test runner keystore setup
card.

fix(testrunner): fix typos on cc test runner

---

package-lock.json
package.json

Update unchained-bitcoin to 0.1.2 in order to fix a transaction bug.
ISSUES: #189

fix(dependencies): update uc-b to 0.1.2

---

src/components/ScriptExplorer/DirectSignatureImporter.jsx

fix(wallet): show bip32path if signing via redeem_script interface

---

src/tests/extendedPublicKeys.jsx
src/tests/publicKeys.jsx
src/tests/signing.jsx

Adjust requirements for test suite expected vs actual for Hermit keys and signing.
Fixes #193

fix(wallet): hermit test suite updates

---

package-lock.json
package.json

Change how commitlint is used to match commitlint best practices.

build(other): rework how commitlint is used

---

.github/workflows/main.yml

Fix release action to only run once

build(other): only run release action once

---

.cz-config.js

Use deps instead of dependencies for commit message scope.

build(other): use deps instead of dependencies

---

package-lock.json
package.json

Upgrade unchained-wallets to 0.1.15 to fix Coldcard wallet config file.

fix(deps): upgrade unchained-wallets to 0.1.15

---

src/components/Wallet/WalletGenerator.jsx

There was a typo on the wallet importer page, this fixes it.

fix(wallet): fix typo on wallet import page

---

package-lock.json
package.json

Update unchained-bitcoin and unchained-wallets to latest version
to include Coldcard informational messages.

fix(deps): update unchained libs to latest version

---

package-lock.json
package.json

Upgrade unchained-bitcoin and unchained-wallets to the latest
versions primarily to fix Ledger WebUSB in MacOS Chrome.

fix(deps): upgrade unchained-libs to latest version

---

.github/workflows/main.yml

Ensure the github action uses node version 12 to build/deploy.

build(other): ensure build uses node version 12

---

.eslintrc
.prettierrc
.travis.yml
package-lock.json
package.json
src/tests/Test.js
src/tests/addresses.jsx
src/tests/ledger.js
src/tests/registration.jsx
src/tests/signing.jsx

Adds new tests for ledger for functionality that's now supported in ledger v2. Adds address check test w/ a couple of fixes to make sure they work. Adds a new test for wallet policy registration that is only supported in ledger v2. Requires updates to fixtures in feature branch: https://github.com/unchained-capital/unchained-bitcoin/tree/ledger-v2

Ledger v2 test suite

---

package.json
src/components/Footer.jsx
src/components/ScriptExplorer/DirectSignatureImporter.jsx
src/components/ScriptExplorer/SignatureImporter.jsx
src/tests/addresses.jsx
src/tests/registration.jsx
src/tests/signing.jsx

WIP branch to get normal signing flows working for ledger v2

feat: update args for ledgerv2 signing

---

README.md

The supported devices in the current README are out-of-date. This PR adds the following supported decides: Trezor Model T, Ledger Nano X, and ColdCards.

chore: 🤖 Update supported devices in README to match Caravan UI

---

CONTRIBUTING.md
src/components/Wallet/ExtendedPublicKeyImporter.jsx
src/reducers/addressReducer.js
src/reducers/quorumReducer.js

addressType conflict not applicable text xpubs. 
(https://github.com/unchained-capital/caravan/issues/305)
(https://github.com/unchained-capital/caravan/issues/305)

Text xpub bip32 conflict fix

---

src/components/App.jsx
vite.config.js

We incorrectly thought during some of the upgrades of our old packages that the hash router was an out of date piece of code that we could remove. I'd forgotten that we needed the hash routing for github pages hosting. D'oh!

fix(build): bring back hash routing

---

package-lock.json

CI doesn't like dependabot comments => https://github.com/unchained-capital/caravan/pull/343

fix(deps): bump @babel/traverse from 7.21.3 to 7.23.2
